package license

const (
	ErrFmtSchema             = "license.Schema: %w"
	ErrFmtPlan               = "license.Plan: %w"
	ErrFmtOffer              = "license.Offer: %w"
	ErrFmtBillingPeriod      = "license.BillingPeriod: %w"
	ErrFmtDeveloperKey       = "license.DeveloperKey: %w"
	ErrFmtDeveloperKeyID     = "license.DeveloperKeyID: %w"
	ErrFmtDeviceLabel        = "license.DeviceLabel: %w"
	ErrFmtAPICallKey         = "license.APICallKey: %w"
	ErrFmtLeaseWindow        = "license.Lease.Window: %w"
	ErrFmtLeaseCheckInWindow = "license.Lease.CheckInWindow: %w"
	ErrFmtLeaseWriteGrace    = "license.Lease.WriteGrace: %w"
	ErrFmtLeaseTrust         = "license.LeaseTrust: %w"
	ErrFmtGateOutcome        = "license.GateOutcome: %w"
	ErrFmtGateReason         = "license.GateReason: %w"
	ErrFmtGateState          = "license.GateState: %w"
	ErrFmtCheckInPayload     = "license.CheckIn.Payload: %w"
	ErrFmtCheckInClient      = "license.CheckIn.Client: %w"
	ErrFmtCheckInEndpoint    = "license.CheckIn.Endpoint: %w"
	ErrFmtCheckInTransport   = "license.CheckIn.Transport: %w"
	ErrFmtCheckInResponse    = "license.CheckIn.Response: %w"
	ErrFmtCheckInRefusal     = "license.CheckIn.Refusal: %w"
)
