package license

const (
	ErrFmtSchema               = "license.Schema: %w"
	ErrFmtPlan                 = "license.Plan: %w"
	ErrFmtOffer                = "license.Offer: %w"
	ErrFmtBillingPeriod        = "license.BillingPeriod: %w"
	ErrFmtDeveloperKey         = "license.DeveloperKey: %w"
	ErrFmtDeveloperKeyID       = "license.DeveloperKeyID: %w"
	ErrFmtDeviceLabel          = "license.DeviceLabel: %w"
	ErrFmtAPICallKey           = "license.APICallKey: %w"
	ErrFmtLeaseWindow          = "license.Lease.Window: %w"
	ErrFmtLeaseCheckInWindow   = "license.Lease.CheckInWindow: %w"
	ErrFmtLeaseWriteGrace      = "license.Lease.WriteGrace: %w"
	ErrFmtLeaseTrust           = "license.LeaseTrust: %w"
	ErrFmtLeaseGeneration      = "license.LeaseGeneration: %w"
	ErrFmtGateOutcome          = "license.GateOutcome: %w"
	ErrFmtGateReason           = "license.GateReason: %w"
	ErrFmtGateInput            = "license.GateInput: %w"
	ErrFmtGateDecision         = "license.GateDecision: %w"
	ErrFmtLeaseState           = "license.LeaseState: %w"
	ErrFmtCheckInPayload       = "license.CheckIn.Payload: %w"
	ErrFmtCheckInClient        = "license.CheckIn.Client: %w"
	ErrFmtCheckInEndpoint      = "license.CheckIn.Endpoint: %w"
	ErrFmtCheckInTransport     = "license.CheckIn.Transport: %w"
	ErrFmtCheckInResponse      = "license.CheckIn.Response: %w"
	ErrFmtCheckInRefusal       = "license.CheckIn.Refusal: %w"
	ErrFmtSeatIdentity         = "license.Seat.Identity: %w"
	ErrFmtSeatInviteAddress    = "license.Seat.InviteAddress: %w"
	ErrFmtSeatInviteToken      = "license.Seat.InviteToken: %w"
	ErrFmtSeatMember           = "license.Seat.Member: %w"
	ErrFmtSeatMemberStatus     = "license.Seat.MemberStatus: %w"
	ErrFmtSeatInvite           = "license.Seat.Invite: %w"
	ErrFmtSeatInviteStatus     = "license.Seat.InviteStatus: %w"
	ErrFmtSeatAssignment       = "license.Seat.Assignment: %w"
	ErrFmtSeatAssignmentStatus = "license.Seat.AssignmentStatus: %w"
	ErrFmtSeatGeneration       = "license.Seat.Generation: %w"
	ErrFmtSeatTransition       = "license.Seat.Transition: %w"
)

const ErrMsgGateInput = "license gate input rejected"
