package license

const (
	jsonFieldBillingPeriod     = "billing_period"
	jsonFieldCheckInAfter      = "check_in_after"
	jsonFieldCheckInBy         = "check_in_by"
	jsonFieldDeveloperKeyID    = "developer_key_id"
	jsonFieldIssuedAt          = "issued_at"
	jsonFieldLeaseNotAfter     = "lease_not_after"
	jsonFieldLeaseID           = "lease_id"
	jsonFieldLeaseGeneration   = "lease_generation"
	jsonFieldPaidUntil         = "paid_until"
	jsonFieldPlan              = "plan"
	jsonFieldPrepaidYears      = "prepaid_years"
	jsonFieldWriteGraceNS      = "write_grace_ns"
	jsonFieldWriter            = "writer"
	jsonFieldOperationSHA256   = "operation_sha256"
	jsonFieldOccurredAt        = "occurred_at"
	jsonFieldRevokedAt         = "revoked_at"
	jsonFieldRequestNonce      = "request_nonce"
	jsonFieldServerObservedAt  = "server_observed_at"
	jsonFieldDecision          = "decision"
	jsonFieldGrant             = "grant"
	jsonFieldWriterRevocations = "writer_revocations"
	jsonFieldTimeCommitment    = "time_commitment"
	jsonFieldUpdateNotice      = "update_notice"
)
