package release

const (
	ErrFmtKind                   = "release.Kind: %w"
	ErrFmtVisibility             = "release.Visibility: %w"
	ErrFmtReleaseID              = "release.ReleaseID: %w"
	ErrFmtReleaseDate            = "release.ReleaseDate: %w"
	ErrFmtArtifactName           = "release.ArtifactName: %w"
	ErrFmtBucket                 = "release.Bucket: %w"
	ErrFmtObjectKey              = "release.ObjectKey: %w"
	ErrFmtDownloadURL            = "release.DownloadURL: %w"
	ErrFmtArchiveLayout          = "release.ArchiveLayout: %w"
	ErrFmtArtifact               = "release.Artifact: %w"
	ErrFmtManifest               = "release.Manifest: %w"
	ErrFmtUploadTarget           = "release.UploadTarget: %w"
	ErrFmtUploadAttemptID        = "release.UploadAttemptID: %w"
	ErrFmtUploadBinding          = "release.UploadBinding: %w"
	ErrFmtUploadReceipt          = "release.UploadReceipt: %w"
	ErrFmtDownloadIndex          = "release.DownloadIndex: %w"
	ErrFmtReleaseRoot            = "release.ReleaseRoot: %w"
	ErrFmtGarbleSeed             = "release.GarbleSeed: %w"
	ErrFmtBuildCommand           = "release.BuildCommand: %w"
	ErrFmtBuildOutput            = "release.BuildOutput: %w"
	ErrFmtBuildTag               = "release.BuildTag: %w"
	ErrFmtLinkerSymbol           = "release.LinkerSymbol: %w"
	ErrFmtBuildPolicy            = "release.BuildPolicy: %w"
	ErrFmtBuildRequest           = "release.BuildRequest: %w"
	ErrFmtReleaseSpec            = "release.ProductReleaseSpec: %w"
	ErrFmtReleasePlan            = "release.ReleasePlan: %w"
	ErrFmtDeployPlan             = "release.DeployPlan: %w"
	ErrFmtDeployRequestID        = "release.DeployRequestID: %w"
	ErrFmtDeployPrepareRequest   = "release.DeployPrepareRequest: %w"
	ErrFmtDeployPrepareResponse  = "release.DeployPrepareResponse: %w"
	ErrFmtDeployFinalizeRequest  = "release.DeployFinalizeRequest: %w"
	ErrFmtDeployFinalizeResponse = "release.DeployFinalizeResponse: %w"
	ErrFmtDeployEndpoints        = "release.DeployEndpoints: %w"
	ErrFmtDeployClient           = "release.DeployClient: %w"
	ErrFmtDeployHTTP             = "release deploy HTTP failure: status=%d: %v"
	ErrFmtDeployAPI              = "release deploy rejected: status=%d code=%s message=%s"
	ErrFmtEvidenceRef            = "release.EvidenceRef: %w"
	ErrFmtGarbleSeedRef          = "release.GarbleSeedRef: %w"
	ErrFmtToolVersion            = "release.ToolVersion: %w"
	ErrFmtToolModule             = "release.ToolModule: %w"
	ErrFmtGoSumHash              = "release.GoSumHash: %w"
	ErrFmtToolchain              = "release.BuildToolchain: %w"
	ErrFmtVulnDB                 = "release.VulnDBSnapshot: %w"
	ErrFmtGateEvidence           = "release.ReleaseGateEvidence: %w"
	ErrFmtToolProvenance         = "release.ToolProvenance: %w"
	ErrFmtPreflight              = "release.ReleasePreflight: %w"
	ErrFmtCommandKind            = "release.CommandKind: %w"
	ErrFmtCommandStatus          = "release.CommandStatus: %w"
	ErrFmtTreeState              = "release.TreeState: %w"
	ErrFmtMachine                = "release.MachineIdentity: %w"
	ErrFmtCommandRun             = "release.CommandRun: %w"
	ErrFmtCustodySeed            = "release.GarbleCustodySeed: %w"
	ErrFmtSeedRequest            = "release.SeedRequest: %w"
	ErrFmtSeedGrant              = "release.SeedGrantBody: %w"
)
