package release

const (
	jsonFieldArtifactCount  = "artifact_count"
	jsonFieldArtifacts      = "artifacts"
	jsonFieldCommit         = "commit"
	jsonFieldCreatedAt      = "created_at"
	jsonFieldDate           = "date"
	jsonFieldDogfood        = "dogfood"
	jsonFieldEvidenceRef    = "evidence_ref"
	jsonFieldFinishedAt     = "finished_at"
	jsonFieldGitCommit      = "git_commit"
	jsonFieldHostnameSHA256 = "hostname_sha256"
	jsonFieldKind           = "kind"
	jsonFieldMachine        = "machine"
	jsonFieldManifests      = "manifests"
	jsonFieldOperatorSHA256 = "operator_sha256"
	jsonFieldPlatform       = "platform"
	jsonFieldPlatforms      = "platforms"
	jsonFieldPrivate        = "private"
	jsonFieldProduct        = "product"
	jsonFieldPublic         = "public"
	jsonFieldReceipts       = "receipts"
	jsonFieldReleaseID      = "release_id"
	jsonFieldRoot           = "root"
	jsonFieldStartedAt      = "started_at"
	jsonFieldStatus         = "status"
	jsonFieldTotalBytes     = "total_bytes"
	jsonFieldTreeState      = "tree_state"
	jsonFieldUserSHA256     = "user_sha256"
	jsonFieldVersion        = "version"
)
