package custody

const (
	ErrFmtULID            = "custody.ULID: %w"
	ErrFmtRelease         = "custody.ReleaseIdentity: %w"
	ErrFmtArtifactName    = "custody.ArtifactName: %w"
	ErrFmtArtifact        = "custody.ArtifactDescriptor: %w"
	ErrFmtObjectPath      = "custody.ObjectPath: %w"
	ErrFmtGeneration      = "custody.Generation: %w"
	ErrFmtStorage         = "custody.Storage: %w"
	ErrFmtRetention       = "custody.Retention: %w"
	ErrFmtOpenRequest     = "custody.SessionOpenRequest: %w"
	ErrFmtOpenResponse    = "custody.SessionOpenResponse: %w"
	ErrFmtUploadedObject  = "custody.UploadedObject: %w"
	ErrFmtFinalize        = "custody.FinalizeRequest: %w"
	ErrFmtReceipt         = "custody.ReceiptBody: %w"
	ErrFmtOpenDisposition = "custody.SessionOpenDisposition: %w"
	ErrFmtTimestamp       = "custody.TimestampProof: %w"
	ErrFmtTimestampQuery  = "custody.RFC3161TimestampQuery: %w"
	ErrFmtTimestampClient = "custody.TimestampClient: %w"
	ErrFmtTimestampHTTP   = "custody timestamp HTTP failure: status=%d: %v"

	ErrFmtEndpoints        = "custody.Endpoints: %w"
	ErrFmtClient           = "custody.Client: %w"
	ErrFmtUploadArtifact   = "custody.UploadArtifact: %w"
	ErrFmtDownloadURL      = "custody.DownloadURL: %w"
	ErrFmtDownloadMethod   = "custody.DownloadMethod: %w"
	ErrFmtDownloadRequest  = "custody.DownloadRequest: %w"
	ErrFmtDownloadTarget   = "custody.DownloadTarget: %w"
	ErrFmtDownloadGrant    = "custody.DownloadGrantBody: %w"
	ErrFmtDownloadArtifact = "custody.DownloadArtifact: %w"
	ErrFmtCustodyHTTP      = "custody API HTTP failure: status=%d: %v"
	ErrFmtCustodyAPI       = "custody API rejected: status=%d code=%s message=%s"
)
